##########################################################################################
#
# Please use env configs only.
# For easy environment configuration modify the ".env" file on the root of this repo.
# For more information read: https://github.com/bkeepers/dotenv
# 
# For an easy start, follow instructions on ".env-example" file at the root of this repo.
# Cheers, Elad.
# 
##########################################################################################

development:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_POST"] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
  
test:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_POST"] %>
