# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  encoding: utf8
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  database: <%= ENV["DATABASE_NAME"] %>
  # host: <%= ENV["DATABASE_HOST"] %>
  # port: <%= ENV["DATABASE_PORT"] %>

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
